name: FetchSpreadsheets

on:
  push:
  pull_request:
  pull_request_target:
  workflow_dispatch:
    inputs:
      api_key:
        description: 'Spreadsheet API Key'
        required: true
        default: ${{ secrets.SPREADSHEET_API_KEY }}
      spreadsheet_ids:
        description: 'Spreadsheets IDs separated by commas'
        required: true
        default: ${{ secrets.SPREADSHEET_IDS }}
      spreadsheet_path:
        description: 'The path where to save the csv'
        required: true
        default: './csv/spreadsheets/'
  schedule:
    - cron:  '0 10 * * *'


jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run spreadsheet fetch
      env:
        SPREADSHEET_API_KEY: ${{ github.event.inputs.api_key }}
        SPREADSHEET_IDS: ${{ github.event.inputs.spreadsheet_ids }}
      run: python -m spreadsheets_fetcher $SPREADSHEET_IDS ${{ github.event.inputs.spreadsheet_path }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Pushing csv files.